### ISSUE TITLE
Vielleicht besser?

### ISSUE THREAD

**Issue by KaroBee** [tpe-lecture/group-04#1]
Hi,
mit ist aufgefallen, dass ihr die Kommentare nicht ganz bis zum Ende durchzieht. Vielleicht kann man da nachhaken? Und ihr habt zwei Methoden für Betrag. Das braucht ihr nicht. Funktioniert so auch, ist aber umständlich.

VG. Karo (Tutor)

**Comment by Semirtt** [comment]
naja klappt nicht ganz, je nachdem welche Betrag methode ich weg mache gibt es fehler meldung im Test
