### ISSUE TITLE
Doppelter Code in Konstruktoren

### ISSUE THREAD

**Issue by KaroBee** [tpe-lecture/group-04#2]
Der leere Konstruktor könnte den anderen Konstruktor mit Vektor(0.0,0.0,0.0) aufrufen. Reduziert die Redundanz von Verweisen auf die Instanzvariablen.

**Comment by Semirtt** [comment]
Es gibt ja einmal den Null-Vektor und deswegen zwei Konstruktoren klar man kann über den einen Vektor nur nullen schreiben dann hat man das selbe, kann aber unserer Meinung nach so einfacher gestalten
