### ISSUE TITLE
multipliziere() hat redundante Zeilen

### ISSUE THREAD

**Issue by KaroBee** [tpe-lecture/group-04#3]
Ein Wert*0 ist 0, es gibt keine erkennbare Notwendigkeit für die erste IF-Abfrage.
Zweite if-Abfrage "if (vektor.a == 0) { vektor.a = 0;}" => Warum? Wenn a schon 0 ist, muss es nicht mehr 0 gemacht werden.

**Comment by Semirtt** [comment]
was machen wir aber dann wenn a nicht 0 ist ? deswegen die abfrage
